## PCA

In [1]:
import numpy as np
from numpy import linalg as lng
from sklearn.decomposition import PCA

In [2]:
X = np.array([[2, 3, 7, 2], [3, 1, 8, 1], [4, 4, 1, 8]]).T
X

array([[2, 3, 4],
       [3, 1, 4],
       [7, 8, 1],
       [2, 1, 8]])

In [3]:
Z = X - np.mean(X, axis=0)
Z

array([[-1.5 , -0.25, -0.25],
       [-0.5 , -2.25, -0.25],
       [ 3.5 ,  4.75, -3.25],
       [-1.5 , -2.25,  3.75]])

In [4]:
cov = Z.T @ Z
cov

array([[ 17.  ,  21.5 , -16.5 ],
       [ 21.5 ,  32.75, -23.25],
       [-16.5 , -23.25,  24.75]])

In [5]:
vals, vects = lng.eig(cov)
vals, vects

(array([67.0063785 ,  1.96944485,  5.52417665]),
 array([[ 0.47626211,  0.83356121,  0.27991089],
        [ 0.67850508, -0.55086348,  0.48598383],
        [-0.55928995,  0.04153473,  0.82793092]]))

In [6]:
print(*reversed(sorted(vals)))
# ¡vectors are columns, not strings!
ord_vects = vects[:, np.argsort(vals)[::-1][:-1]]
ord_vects

67.00637849713772 5.524176651329199 1.9694448515330876


array([[ 0.47626211,  0.27991089],
       [ 0.67850508,  0.48598383],
       [-0.55928995,  0.82793092]])

In [7]:
Z @ ord_vects

array([[-0.74419695, -0.74834502],
       [-1.624945  , -1.44040179],
       [ 6.70750889,  0.59733579],
       [-4.33836693,  1.59141101]])

In [8]:
# explained variance (absolute and ratio)
max(vals) / len(vals), vals[np.argsort(vals)][-2] / len(vals), max(vals) / sum(vals), vals[np.argsort(vals)][-2] / sum(vals)

(22.335459499045907, 1.841392217109733, 0.8994144764716472, 0.0741500221654926)

In [9]:
(67.00637849713772 + 5.524176651329199) / (67.00637849713772 + 5.524176651329199 + 1.9694448515330876)

0.9735644986371398

In [10]:
pca = PCA(2)
pca.fit_transform(X)

array([[-0.74419695, -0.74834502],
       [-1.624945  , -1.44040179],
       [ 6.70750889,  0.59733579],
       [-4.33836693,  1.59141101]])

In [11]:
pca.explained_variance_, pca.explained_variance_ratio_, pca.components_

(array([22.3354595 ,  1.84139222]),
 array([0.89941448, 0.07415002]),
 array([[ 0.47626211,  0.67850508, -0.55928995],
        [ 0.27991089,  0.48598383,  0.82793092]]))

## SVD

In [3]:
np.set_printoptions(suppress=True)

In [4]:
X

array([[2, 3, 4],
       [3, 1, 4],
       [7, 8, 1],
       [2, 1, 8]])

In [5]:
mult = X @ X.T
mult

array([[ 29,  25,  42,  39],
       [ 25,  26,  33,  39],
       [ 42,  33, 114,  30],
       [ 39,  39,  30,  69]])

In [6]:
cov = X.T @ X
cov

array([[66, 67, 43],
       [67, 75, 32],
       [43, 32, 97]])

In [7]:
vals_v, vects_v = lng.eig(cov)
vals_v, vects_v

(array([174.02054492,   2.12198065,  61.85747443]),
 array([[-0.58519009, -0.75739868, -0.28965463],
        [-0.57931925,  0.64043083, -0.50421975],
        [-0.56739912,  0.12726189,  0.81354941]]))

In [17]:
vals, vects_u = lng.eig(mult)
vals, vects_u

(array([174.02054492,  61.85747443,  -0.        ,   2.12198065]),
 array([[ 0.39251502,  0.1477732 ,  0.65504047,  0.6285038 ],
        [ 0.34904458,  0.23916407,  0.47639307, -0.77072568],
        [ 0.70485946, -0.66723748, -0.23819653, -0.035067  ],
        [ 0.47673156,  0.68975196, -0.5359422 ,  0.09866715]]))

In [18]:
# for having python unprecise after the 16th number, convert to 0 all that became negative
sigma = np.diag(np.sqrt(np.maximum(0, list(reversed(sorted(vals))))))[:X.shape[0], :X.shape[1]]
sigma

array([[13.19168469,  0.        ,  0.        ],
       [ 0.        ,  7.86495228,  0.        ],
       [ 0.        ,  0.        ,  1.45670198],
       [ 0.        ,  0.        ,  0.        ]])

In [19]:
U = vects_u[:, np.argsort(vals)[::-1]]
U

array([[ 0.39251502,  0.1477732 ,  0.6285038 ,  0.65504047],
       [ 0.34904458,  0.23916407, -0.77072568,  0.47639307],
       [ 0.70485946, -0.66723748, -0.035067  , -0.23819653],
       [ 0.47673156,  0.68975196,  0.09866715, -0.5359422 ]])

In [20]:
Vt = vects_v[:, np.argsort(vals_v)[::-1]].T
Vt

array([[-0.58519009, -0.57931925, -0.56739912],
       [-0.28965463, -0.50421975,  0.81354941],
       [-0.75739868,  0.64043083,  0.12726189]])

In [21]:
X @ Vt.T, U @ sigma
Vt *= np.transpose([[-1, 1, 1]])
X @ Vt.T, U @ sigma

(array([[ 5.17793443,  1.16222915,  0.91554272],
        [ 4.60448601,  1.88101401, -1.12271762],
        [ 9.29828374, -5.24779097, -0.05108217],
        [ 6.28889243,  5.42486628,  0.14372863]]),
 array([[ 5.17793443,  1.16222915,  0.91554272],
        [ 4.60448601,  1.88101401, -1.12271762],
        [ 9.29828374, -5.24779097, -0.05108217],
        [ 6.28889243,  5.42486628,  0.14372863]]))

In [22]:
np.allclose(X.T @ U, Vt.T @ sigma.T)

True

In [26]:
lng.svd(X)

(array([[-0.39251502,  0.1477732 , -0.6285038 , -0.65504047],
        [-0.34904458,  0.23916407,  0.77072568, -0.47639307],
        [-0.70485946, -0.66723748,  0.035067  ,  0.23819653],
        [-0.47673156,  0.68975196, -0.09866715,  0.5359422 ]]),
 array([13.19168469,  7.86495228,  1.45670198]),
 array([[-0.58519009, -0.57931925, -0.56739912],
        [-0.28965463, -0.50421975,  0.81354941],
        [ 0.75739868, -0.64043083, -0.12726189]]))

In [23]:
U, sigma, Vt

(array([[ 0.39251502,  0.1477732 ,  0.6285038 ,  0.65504047],
        [ 0.34904458,  0.23916407, -0.77072568,  0.47639307],
        [ 0.70485946, -0.66723748, -0.035067  , -0.23819653],
        [ 0.47673156,  0.68975196,  0.09866715, -0.5359422 ]]),
 array([[13.19168469,  0.        ,  0.        ],
        [ 0.        ,  7.86495228,  0.        ],
        [ 0.        ,  0.        ,  1.45670198],
        [ 0.        ,  0.        ,  0.        ]]),
 array([[ 0.58519009,  0.57931925,  0.56739912],
        [-0.28965463, -0.50421975,  0.81354941],
        [-0.75739868,  0.64043083,  0.12726189]]))

In [17]:
U @ sigma @ Vt

array([[2., 3., 4.],
       [3., 1., 4.],
       [7., 8., 1.],
       [2., 1., 8.]])

In [27]:
Vt @ Vt.T

array([[ 1.00000000e+00, -1.78165618e-16, -6.58294453e-16],
       [-1.78165618e-16,  1.00000000e+00, -1.49243978e-16],
       [-6.58294453e-16, -1.49243978e-16,  1.00000000e+00]])

In [28]:
Vt.T @ Vt

array([[ 1.00000000e+00,  1.38190060e-16,  2.84550011e-16],
       [ 1.38190060e-16,  1.00000000e+00, -3.86088011e-16],
       [ 2.84550011e-16, -3.86088011e-16,  1.00000000e+00]])